# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Article.create(
  title: "Team Rocket Foiled Again! Ash and Pikachu Save Cerulean City Gym!",
  content: "In the heart of Cerulean City, where the shimmering waters of the city's famous gym glistened under the sunlight, an attempted heist by the notorious Team Rocket sent shockwaves through the tranquil streets. The nefarious trio, Jessie, James, and their loyal Meowth, had set their sights on stealing the prized Water-type Pokémon held within the gym. However, their plans were swiftly thwarted by the timely intervention of Ash Ketchum, the determined Pokémon trainer from Pallet Town, and his loyal partner Pikachu. With lightning-fast reflexes and unwavering courage, Ash and Pikachu sprang into action, determined to protect the gym and its inhabitants from Team Rocket's villainous schemes. As Team Rocket attempted to make off with their ill-gotten gains, Ash and Pikachu engaged them in a fierce battle, their determination to defend Cerulean City burning bright in their eyes. With each thunderous attack and electrifying bolt of lightning, they drove Team Rocket back, refusing to yield to their underhanded tactics. Despite Team Rocket's best efforts, Ash and Pikachu emerged victorious, sending the trio blasting off into the distant horizon with a resounding crash. The citizens of Cerulean City cheered as Ash and Pikachu stood triumphant, their bravery and heroism earning them the admiration and gratitude of all who witnessed their valiant deeds. With Team Rocket's plans foiled once again, Cerulean City Gym remained safe and secure, thanks to the quick thinking and courageous actions of Ash and Pikachu. As the sun set over the tranquil waters of Cerulean City, casting a warm glow over the cityscape, Ash and Pikachu basked in the glow of their hard-fought victory, knowing that they had once again saved the day and proven that true friendship and bravery could overcome even the most dastardly of adversaries."
)

Article.create(
  title: "Fuchsia City's Shiny Spectacle: Trainers Flock to Special Day Celebrating Rare Pokémon!",
  content: "In the heart of Fuchsia City, with its vibrant colors and surrounding forests, an atmosphere of excitement and anticipation filled the air. Today marked a special occasion, one eagerly awaited by trainers and Pokémon enthusiasts from far and wide – the annual Shiny Pokémon Celebration Day.
  The origins of this event traced back to a tradition established by the diligent efforts of Fuchsia City's Pokémon experts and caretakers. Recognizing the city's unique allure and charm, the local Pokémon Center and Safari Zone collaborated to create an extraordinary experience for visitors and residents alike.
  Months of meticulous preparation culminated in the transformation of the Safari Zone's enclosures into showcases for rare and elusive Shiny Pokémon. With the assistance of skilled Pokémon trainers and researchers, a diverse array of Shiny specimens were carefully curated and placed on display for the public to admire.
  From the resplendent golden scales of a Shiny Dragonite to the shimmering pink fur of a rare Espeon, each enclosure housed a breathtaking selection of Pokémon, their radiant colors standing out amidst the verdant backdrop of the Safari Zone.
  As word of the event spread, trainers from neighboring regions flocked to Fuchsia City, eager to witness the spectacle firsthand and perhaps catch a glimpse of their favorite Shiny Pokémon. Among the trainers drawn to Fuchsia City for the event was Lance, the renowned Dragon-type Pokémon Champion. Known for his deep admiration for Shiny Pokémon, Lance was particularly captivated by the majestic Shiny Dragonite on display. Lance marveled at the rare creature, admiring its beauty and strength.
  Throughout the day, guided tours and educational seminars provided visitors with insights into the biology and behavior of Shiny Pokémon, fostering a deeper appreciation for these rare and cherished creatures. Meanwhile, friendly competitions and games offered opportunities for trainers to test their skills and bond with their Pokémon companions",
)
